language: node_js
node_js:
	- "9"
dist: trusty
sudo: required
branches:
	only:
		- master
before_script:
	- npm install -g @angular/cli
script:
	- ng lint
	- ng build --prod --base-href https://travis-ci.org/viperdigo/orcav2
deploy:
	provider: pages
	skip_cleanup: true
	github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
	keep_history: true
	on:
		branch: master
