version: '3.3'
services:
  front-metronic-angular:
    image: orcaplus/front:latest
    ports:
     - 3000:3000
    networks:
     - default
    command: ["ng", "serve"]
networks:
  default:
    driver: overlay
